name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci
        working-directory: src/hunterstack-chain
        run: npm ci
      - name: npm run lint && npm run build
        working-directory: src/hunterstack-chain
        run: npm run lint && npm run build